const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Tween,
		C3.Plugins.TiledBg,
		C3.Behaviors.Pathfinding,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.Arr,
		C3.Plugins.AJAX,
		C3.Plugins.Json,
		C3.Plugins.Browser,
		C3.Plugins.TextBox,
		C3.Behaviors.Anchor,
		C3.Behaviors.scrollto,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Behaviors.MoveTo.Cnds.IsMoving,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.While,
		C3.Plugins.Arr.Cnds.CompareSize,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Arr.Cnds.CompareX,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.ScriptsInEvents.EventSheet1_Event37_Act3,
		C3.Plugins.TiledBg.Acts.SetHeight,
		C3.Plugins.TiledBg.Acts.SetAngle,
		C3.ScriptsInEvents.EventSheet1_Event40_Act3,
		C3.ScriptsInEvents.EventSheet1_Event41_Act1,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.ScriptsInEvents.EventSheet1_Event59_Act1,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.ScriptsInEvents.EventSheet1_Event62_Act1,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.System.Exps.viewportmidy,
		C3.Plugins.System.Exps.viewporttop,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout
	];
};
self.C3_JsPropNameTable = [
	{board: 0},
	{CurrentX: 0},
	{CurrentY: 0},
	{Position: 0},
	{MoveTo: 0},
	{Tween: 0},
	{Player: 0},
	{snake: 0},
	{ladder: 0},
	{TiledBackground: 0},
	{Index: 0},
	{SnakeEntry: 0},
	{LadderEntry: 0},
	{LadderrExit: 0},
	{LadderId: 0},
	{SnakeExit: 0},
	{SnakeId: 0},
	{Islast: 0},
	{Pathfinding: 0},
	{Box: 0},
	{snakeladdersc3screenshot: 0},
	{TextPosition: 0},
	{DiceAnimationgif: 0},
	{Enabled: 0},
	{btnSubmit: 0},
	{Touch: 0},
	{Audio: 0},
	{shadow: 0},
	{ArraySnakes: 0},
	{ArrayLadders: 0},
	{AJAX: 0},
	{JSON: 0},
	{Browser: 0},
	{LadderTile: 0},
	{TiledBackground2: 0},
	{TextInput: 0},
	{WinDialog: 0},
	{text3: 0},
	{blackOverlay: 0},
	{TextAdConfirm: 0},
	{BtnOK: 0},
	{Anchor: 0},
	{BgSprite: 0},
	{Text2: 0},
	{pngwingcom: 0},
	{ScrollTo: 0},
	{Cam: 0},
	{sfxVolume: 0},
	{musicVolume: 0},
	{isMusic: 0},
	{isSFX: 0},
	{numLadders: 0},
	{numSnakes: 0},
	{maxPositions: 0},
	{boardWidth: 0},
	{cellWidth: 0},
	{boardStartX: 0},
	{boardStartY: 0},
	{gridSize: 0},
	{DiceValue: 0},
	{rand_anim_frame: 0},
	{count: 0},
	{dir: 0},
	{frame: 0},
	{startX: 0},
	{startY: 0},
	{start: 0},
	{end: 0},
	{returnValue: 0},
	{endX: 0},
	{endY: 0},
	{position: 0},
	{name: 0},
	{tag: 0},
	{vol: 0},
	{loop: 0},
	{roll: 0},
	{flag: 0},
	{targetX: 0},
	{targetY: 0},
	{pos: 0},
	{remainingSteps: 0},
	{initX: 0},
	{initY: 0},
	{EndX: 0},
	{EndY: 0},
	{Count: 0},
	{snakesCount: 0},
	{laddersCount: 0},
	{show: 0}
];

self.InstanceType = {
	board: class extends self.ISpriteInstance {},
	Player: class extends self.ISpriteInstance {},
	snake: class extends self.ISpriteInstance {},
	ladder: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Box: class extends self.ISpriteInstance {},
	snakeladdersc3screenshot: class extends self.ISpriteInstance {},
	TextPosition: class extends self.ITextInstance {},
	DiceAnimationgif: class extends self.ISpriteInstance {},
	btnSubmit: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	shadow: class extends self.ISpriteInstance {},
	ArraySnakes: class extends self.IArrayInstance {},
	ArrayLadders: class extends self.IArrayInstance {},
	AJAX: class extends self.IInstance {},
	JSON: class extends self.IJSONInstance {},
	Browser: class extends self.IInstance {},
	LadderTile: class extends self.ITiledBackgroundInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	TextInput: class extends self.ITextInputInstance {},
	WinDialog: class extends self.ISpriteInstance {},
	text3: class extends self.ISpriteInstance {},
	blackOverlay: class extends self.ISpriteInstance {},
	TextAdConfirm: class extends self.ITextInstance {},
	BtnOK: class extends self.ISpriteInstance {},
	BgSprite: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	pngwingcom: class extends self.ISpriteInstance {},
	Cam: class extends self.ISpriteInstance {}
}