const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Text,
		C3.Plugins.Sprite,
		C3.Behaviors.Pin,
		C3.Plugins.TextBox,
		C3.Behaviors.Turret,
		C3.Behaviors.Tween,
		C3.Plugins.Tilemap,
		C3.Plugins.TiledBg,
		C3.Behaviors.scrollto,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Plugins.Particles,
		C3.Behaviors.Sin,
		C3.Behaviors.solid,
		C3.Plugins.Touch,
		C3.Plugins.Keyboard,
		C3.Plugins.gamepad,
		C3.Plugins.Browser,
		C3.Plugins.Arr,
		C3.Behaviors.Rotate,
		C3.Behaviors.LOS,
		C3.Behaviors.Platform,
		C3.Behaviors.Timer,
		C3.Behaviors.Anchor,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.TextBox.Acts.SetCSSStyle,
		C3.Plugins.TextBox.Acts.SetElemAttribute,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.TextBox.Cnds.CompareText,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.PickByEvaluate,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Touch.Cnds.OnNthTouchStart,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.System.Cnds.ForEach,
		C3.Behaviors.Turret.Acts.SetTargetMode,
		C3.Behaviors.Turret.Acts.AddTarget,
		C3.Behaviors.Turret.Acts.SetRange,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Particles.Acts.RemoveFromParent,
		C3.Plugins.System.Acts.CreateObjectByName,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Particles.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.PickLastCreated,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.gamepad.Cnds.IsButtonDown,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.Particles.Acts.SetRate,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Behaviors.Platform.Exps.VectorX,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Exps.ImageWidth,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.ImageHeight,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Bullet.Exps.Speed,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Turret.Cnds.OnShoot,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Exps.loopindex,
		C3.Behaviors.Bullet.Cnds.CompareTravelled,
		C3.Behaviors.Turret.Exps.Range,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Exps.Height,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgbex255,
		C3.Plugins.System.Acts.SetLayoutScale,
		C3.Plugins.System.Acts.SetLayerInteractive
	];
};
self.C3_JsPropNameTable = [
	{Name: 0},
	{Id: 0},
	{HTextPlayers: 0},
	{MMBtnStart: 0},
	{TextCharaterName1: 0},
	{TextCharaterName2: 0},
	{TextSelCharaterName: 0},
	{MMBtnCharacter: 0},
	{Selected: 0},
	{Pin: 0},
	{Characters_Idle: 0},
	{MMBtnSave: 0},
	{TextInput: 0},
	{Turret: 0},
	{Turret1: 0},
	{TeamId: 0},
	{Turret2: 0},
	{HitPoints: 0},
	{Tower: 0},
	{Warrior_Blue: 0},
	{Warrior_Red: 0},
	{Archer_Blue: 0},
	{Archer_Red: 0},
	{Arrow_Blue: 0},
	{Biker_Gun: 0},
	{Biker_Hand_Left: 0},
	{Biker_Hand_Right: 0},
	{Biker_Knife: 0},
	{Biker_Gun1: 0},
	{Punk_Knife: 0},
	{Cyborg_Knife: 0},
	{GunType: 0},
	{PlayerCollision: 0},
	{Tween: 0},
	{Gem1: 0},
	{Gem2: 0},
	{Type: 0},
	{Tilemap: 0},
	{TiledBackground: 0},
	{Overlay: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{TitleScreensOverlay: 0},
	{ScrollTo: 0},
	{Background: 0},
	{TiledBackground1: 0},
	{TiledBackground2: 0},
	{TiledBackground3: 0},
	{TiledBackground4: 0},
	{Button: 0},
	{Camera: 0},
	{Bullet: 0},
	{DestroyOutsideLayout: 0},
	{Projectile: 0},
	{TowerId: 0},
	{RangeMarker: 0},
	{Dust: 0},
	{Fire: 0},
	{Sine: 0},
	{Flare: 0},
	{Solid: 0},
	{GroundCollider: 0},
	{GroundTextures: 0},
	{Shockwave: 0},
	{Sprite: 0},
	{Touch: 0},
	{Keyboard: 0},
	{Gamepad: 0},
	{Browser: 0},
	{ArrayCharactersName: 0},
	{ArrayWeaponName: 0},
	{HTextMisc: 0},
	{HTextMisc2: 0},
	{HTextMiscWepanName: 0},
	{Explosions: 0},
	{Index: 0},
	{IsSelected: 0},
	{LobbyPlayersBG: 0},
	{ArroeIcon: 0},
	{Character_Selection_UI: 0},
	{Rotate: 0},
	{LightFlare: 0},
	{BG_Background: 0},
	{Sprite4: 0},
	{LineOfSight: 0},
	{Gun: 0},
	{Platform: 0},
	{Timer: 0},
	{PlayersTeam1: 0},
	{Towers: 0},
	{Gems: 0},
	{FlashEffect: 0},
	{Characters: 0},
	{Arrow: 0},
	{Anchor: 0},
	{TileMapBg: 0},
	{Hand: 0},
	{BackgroundSprite: 0},
	{playerName: 0},
	{ColorName: 0},
	{CharacterType: 0},
	{CharacterName: 0},
	{MyTeamId: 0},
	{SelectedWeaponId: 0},
	{WeaponName: 0},
	{uid: 0},
	{SelectedTeamId: 0},
	{CharacterScale: 0},
	{InputLeft: 0},
	{InputRight: 0},
	{InputUp: 0},
	{InputDown: 0},
	{HorizontalAxis: 0},
	{VerticalAxis: 0},
	{PlayerDirection: 0},
	{LookingAngle: 0},
	{TargetUID: 0},
	{Damage: 0},
	{ObjectUID: 0},
	{Duration: 0},
	{Intensity: 0},
	{WIDTH: 0},
	{activate: 0},
	{layer_name: 0},
	{group_name: 0}
];

self.InstanceType = {
	HTextPlayers: class extends self.ITextInstance {},
	MMBtnStart: class extends self.ISpriteInstance {},
	TextCharaterName1: class extends self.ITextInstance {},
	TextCharaterName2: class extends self.ITextInstance {},
	TextSelCharaterName: class extends self.ITextInstance {},
	MMBtnCharacter: class extends self.ISpriteInstance {},
	Characters_Idle: class extends self.ISpriteInstance {},
	MMBtnSave: class extends self.ISpriteInstance {},
	TextInput: class extends self.ITextInputInstance {},
	Turret1: class extends self.ISpriteInstance {},
	Turret2: class extends self.ISpriteInstance {},
	Tower: class extends self.ISpriteInstance {},
	Warrior_Blue: class extends self.ISpriteInstance {},
	Warrior_Red: class extends self.ISpriteInstance {},
	Archer_Blue: class extends self.ISpriteInstance {},
	Archer_Red: class extends self.ISpriteInstance {},
	Arrow_Blue: class extends self.ISpriteInstance {},
	Biker_Gun: class extends self.ISpriteInstance {},
	Biker_Hand_Left: class extends self.ISpriteInstance {},
	Biker_Hand_Right: class extends self.ISpriteInstance {},
	Biker_Knife: class extends self.ISpriteInstance {},
	Biker_Gun1: class extends self.ISpriteInstance {},
	Punk_Knife: class extends self.ISpriteInstance {},
	Cyborg_Knife: class extends self.ISpriteInstance {},
	PlayerCollision: class extends self.ISpriteInstance {},
	Gem1: class extends self.ISpriteInstance {},
	Gem2: class extends self.ISpriteInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Overlay: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	TitleScreensOverlay: class extends self.ISpriteInstance {},
	Background: class extends self.ISpriteInstance {},
	TiledBackground1: class extends self.ITiledBackgroundInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {},
	Button: class extends self.ISpriteInstance {},
	Camera: class extends self.ISpriteInstance {},
	Projectile: class extends self.ISpriteInstance {},
	RangeMarker: class extends self.ISpriteInstance {},
	Dust: class extends self.IParticlesInstance {},
	Fire: class extends self.ISpriteInstance {},
	Flare: class extends self.ISpriteInstance {},
	GroundCollider: class extends self.ISpriteInstance {},
	GroundTextures: class extends self.ISpriteInstance {},
	Shockwave: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Gamepad: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	ArrayCharactersName: class extends self.IArrayInstance {},
	ArrayWeaponName: class extends self.IArrayInstance {},
	HTextMisc: class extends self.ITextInstance {},
	HTextMisc2: class extends self.ITextInstance {},
	HTextMiscWepanName: class extends self.ITextInstance {},
	Explosions: class extends self.ISpriteInstance {},
	LobbyPlayersBG: class extends self.ISpriteInstance {},
	ArroeIcon: class extends self.ISpriteInstance {},
	Character_Selection_UI: class extends self.ISpriteInstance {},
	LightFlare: class extends self.ISpriteInstance {},
	BG_Background: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Gun: class extends self.ISpriteInstance {},
	PlayersTeam1: class extends self.ISpriteInstance {},
	Towers: class extends self.ISpriteInstance {},
	Gems: class extends self.ISpriteInstance {},
	FlashEffect: class extends self.ISpriteInstance {},
	Characters: class extends self.ISpriteInstance {},
	Arrow: class extends self.ISpriteInstance {},
	TileMapBg: class extends self.ITiledBackgroundInstance {},
	Hand: class extends self.ISpriteInstance {},
	BackgroundSprite: class extends self.ISpriteInstance {}
}