const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Tween,
		C3.Plugins.TiledBg,
		C3.Behaviors.Pathfinding,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.Arr,
		C3.Plugins.AJAX,
		C3.Plugins.Browser,
		C3.Plugins.TextBox,
		C3.Behaviors.Anchor,
		C3.Behaviors.scrollto,
		C3.Plugins.List,
		C3.Plugins.Multiplayer,
		C3.Plugins.Button,
		C3.Plugins.Keyboard,
		C3.Plugins.Dictionary,
		C3.Plugins.Json,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.While,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Arr.Cnds.CompareX,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.ScriptsInEvents.Es_game_Event23_Act3,
		C3.Plugins.TiledBg.Acts.SetHeight,
		C3.Plugins.TiledBg.Acts.SetAngle,
		C3.ScriptsInEvents.Es_game_Event26_Act3,
		C3.ScriptsInEvents.Es_game_Event27_Act1,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Arr.Cnds.CompareSize,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Arr.Acts.Push,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.ScriptsInEvents.Es_game_Event57_Act1,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Exps.viewportmidy,
		C3.Plugins.Multiplayer.Exps.MyID,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Arr.Exps.CurX,
		C3.Plugins.Arr.Exps.CurValue,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.TextBox.Acts.SetElemAttribute,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.TextBox.Acts.SetPos,
		C3.Plugins.Text.Exps.X,
		C3.Plugins.Text.Exps.Width,
		C3.Plugins.Text.Exps.Y,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.TextBox.Cnds.OnTextChanged,
		C3.Plugins.TextBox.Acts.SetCSSStyle,
		C3.Plugins.TextBox.Cnds.CompareText,
		C3.Plugins.Multiplayer.Cnds.IsSupported,
		C3.Plugins.System.Exps.viewportmidx,
		C3.Plugins.Text.Acts.SetY,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Plugins.Text.Acts.AppendText,
		C3.Plugins.Multiplayer.Acts.SignallingConnect,
		C3.Plugins.Multiplayer.Cnds.OnSignallingConnected,
		C3.Plugins.Multiplayer.Acts.SignallingLogin,
		C3.Plugins.Multiplayer.Cnds.OnSignallingLoggedIn,
		C3.Plugins.Multiplayer.Exps.MyAlias,
		C3.Plugins.Multiplayer.Acts.SignallingAutoJoinRoom,
		C3.Plugins.Multiplayer.Cnds.OnSignallingJoinedRoom,
		C3.Plugins.Multiplayer.Cnds.IsHost,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.Multiplayer.Cnds.OnSignallingLeftRoom,
		C3.Plugins.Multiplayer.Cnds.OnSignallingDisconnected,
		C3.Plugins.Multiplayer.Cnds.OnSignallingError,
		C3.Plugins.Multiplayer.Exps.ErrorMessage,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Multiplayer.Cnds.OnPeerConnected,
		C3.Plugins.Multiplayer.Exps.PeerAlias,
		C3.Plugins.Multiplayer.Exps.PeerID,
		C3.Plugins.Multiplayer.Cnds.OnPeerDisconnected,
		C3.Plugins.Dictionary.Cnds.HasKey,
		C3.Plugins.Dictionary.Acts.DeleteKey,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Multiplayer.Acts.SendPeerMessage,
		C3.Plugins.Text.Cnds.CompareText,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Multiplayer.Cnds.OnHostDisconnected,
		C3.Plugins.TextBox.Acts.SetEnabled,
		C3.Plugins.Button.Acts.SetEnabled,
		C3.Plugins.List.Acts.Clear,
		C3.Plugins.Multiplayer.Cnds.OnPeerMessage,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Multiplayer.Exps.FromID,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Multiplayer.Exps.Message,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.Dictionary.Acts.JSONLoad,
		C3.Plugins.Dictionary.Cnds.ForEachKey,
		C3.Plugins.Dictionary.Exps.CurrentKey,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Multiplayer.Exps.FromAlias,
		C3.Plugins.Multiplayer.Acts.HostBroadcastMessage,
		C3.Plugins.Dictionary.Exps.KeyCount,
		C3.Plugins.Multiplayer.Exps.HostID,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Dictionary.Exps.AsJSON,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Dictionary.Exps.CurrentValue,
		C3.Plugins.Touch.Cnds.OnDoubleTapGesture,
		C3.Plugins.Browser.Acts.RequestFullScreen
	];
};
self.C3_JsPropNameTable = [
	{Gap: 0},
	{Position: 0},
	{Index: 0},
	{IsActive: 0},
	{Selected: 0},
	{Id: 0},
	{Name: 0},
	{MoveTo: 0},
	{Tween: 0},
	{Player: 0},
	{ladder: 0},
	{TiledBackground: 0},
	{SnakeEntry: 0},
	{LadderEntry: 0},
	{LadderrExit: 0},
	{LadderId: 0},
	{SnakeExit: 0},
	{SnakeId: 0},
	{Islast: 0},
	{Pathfinding: 0},
	{Box: 0},
	{TextPosition: 0},
	{DiceAnimationgif: 0},
	{Enabled: 0},
	{btnSubmit: 0},
	{Touch: 0},
	{Audio: 0},
	{shadow: 0},
	{ArraySnakes: 0},
	{ArrayLadders: 0},
	{AJAX: 0},
	{Browser: 0},
	{LadderTile: 0},
	{TiledBackground2: 0},
	{TextInput: 0},
	{WinDialog: 0},
	{text3: 0},
	{blackOverlay: 0},
	{TextAdConfirm: 0},
	{BtnOK: 0},
	{Anchor: 0},
	{BgSprite: 0},
	{TextDiceValue: 0},
	{ScrollTo: 0},
	{Cam: 0},
	{TitleScreensOverlay: 0},
	{Enable: 0},
	{BtnNext: 0},
	{TextMisc: 0},
	{IsSelected: 0},
	{LobbyPlayersBG: 0},
	{ArroeIcon: 0},
	{TextReady: 0},
	{ArrayPlayerIDs: 0},
	{ArrayPlayerColors: 0},
	{GameType: 0},
	{List: 0},
	{LabelText: 0},
	{InputTextPlayerCount: 0},
	{LabelText2: 0},
	{TextPlayers: 0},
	{Multiplayer: 0},
	{TextLobbyHeading: 0},
	{ChatLog: 0},
	{ChatTextBox: 0},
	{PeerList: 0},
	{SendButton: 0},
	{Keyboard: 0},
	{DictPlayers: 0},
	{DictPlayersColor: 0},
	{ArrayColors: 0},
	{TextMisc3: 0},
	{DictREadyStates: 0},
	{JSON2: 0},
	{Text: 0},
	{Player2: 0},
	{sfxVolume: 0},
	{musicVolume: 0},
	{isMusic: 0},
	{isSFX: 0},
	{numLadders: 0},
	{numSnakes: 0},
	{maxPositions: 0},
	{boardWidth: 0},
	{cellWidth: 0},
	{boardStartX: 0},
	{boardStartY: 0},
	{gridSize: 0},
	{DiceValue: 0},
	{CurrentTurn: 0},
	{count: 0},
	{dir: 0},
	{frame: 0},
	{startX: 0},
	{startY: 0},
	{returnValue: 0},
	{start: 0},
	{end: 0},
	{endX: 0},
	{endY: 0},
	{position: 0},
	{name: 0},
	{tag: 0},
	{vol: 0},
	{loop: 0},
	{remainder: 0},
	{flag: 0},
	{targetX: 0},
	{targetY: 0},
	{remainingSteps: 0},
	{direct: 0},
	{show: 0},
	{gapFactor: 0},
	{activate: 0},
	{layer_name: 0},
	{group_name: 0},
	{playerName: 0},
	{uid: 0},
	{y: 0},
	{gap: 0},
	{PlayersCount: 0},
	{SelectedPlayerColor: 0},
	{SelectedGameType: 0},
	{MyUsername: 0},
	{MyId: 0},
	{MyColor: 0},
	{ROOM_NAME: 0},
	{GAME_NAME: 0},
	{INSTANCE_NAME: 0},
	{MAX_PLAYERS: 0},
	{message: 0},
	{ind: 0}
];

self.InstanceType = {
	Player: class extends self.ISpriteInstance {},
	ladder: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Box: class extends self.ISpriteInstance {},
	TextPosition: class extends self.ITextInstance {},
	DiceAnimationgif: class extends self.ISpriteInstance {},
	btnSubmit: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	shadow: class extends self.ISpriteInstance {},
	ArraySnakes: class extends self.IArrayInstance {},
	ArrayLadders: class extends self.IArrayInstance {},
	AJAX: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	LadderTile: class extends self.ITiledBackgroundInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	TextInput: class extends self.ITextInputInstance {},
	WinDialog: class extends self.ISpriteInstance {},
	text3: class extends self.ISpriteInstance {},
	blackOverlay: class extends self.ISpriteInstance {},
	TextAdConfirm: class extends self.ITextInstance {},
	BtnOK: class extends self.ISpriteInstance {},
	BgSprite: class extends self.ISpriteInstance {},
	TextDiceValue: class extends self.ITextInstance {},
	Cam: class extends self.ISpriteInstance {},
	TitleScreensOverlay: class extends self.ISpriteInstance {},
	BtnNext: class extends self.ISpriteInstance {},
	TextMisc: class extends self.ITextInstance {},
	LobbyPlayersBG: class extends self.ISpriteInstance {},
	ArroeIcon: class extends self.ISpriteInstance {},
	TextReady: class extends self.ITextInstance {},
	ArrayPlayerIDs: class extends self.IArrayInstance {},
	ArrayPlayerColors: class extends self.IArrayInstance {},
	GameType: class extends self.IArrayInstance {},
	List: class extends self.IListInstance {},
	LabelText: class extends self.ITextInstance {},
	InputTextPlayerCount: class extends self.ITextInputInstance {},
	LabelText2: class extends self.ITextInstance {},
	TextPlayers: class extends self.ITextInstance {},
	Multiplayer: class extends self.IInstance {},
	TextLobbyHeading: class extends self.ITextInstance {},
	ChatLog: class extends self.ITextInputInstance {},
	ChatTextBox: class extends self.ITextInputInstance {},
	PeerList: class extends self.IListInstance {},
	SendButton: class extends self.IButtonInstance {},
	Keyboard: class extends self.IInstance {},
	DictPlayers: class extends self.IDictionaryInstance {},
	DictPlayersColor: class extends self.IDictionaryInstance {},
	ArrayColors: class extends self.IArrayInstance {},
	TextMisc3: class extends self.ITextInstance {},
	DictREadyStates: class extends self.IDictionaryInstance {},
	JSON2: class extends self.IJSONInstance {},
	Text: class extends self.ITextInstance {},
	Player2: class extends self.ISpriteInstance {}
}