const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Plugins.Particles,
		C3.Behaviors.Tween,
		C3.Behaviors.Rotate,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Text.Acts.SetText,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Exps.viewportmidx,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.CreateObjectByName,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.right,
		C3.Plugins.Sprite.Exps.ObjectTypeName,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Behaviors.Sin.Cnds.IsEnabled,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Behaviors.Tween.Acts.TweenTwoProperties
	];
};
self.C3_JsPropNameTable = [
	{InitY: 0},
	{TopY: 0},
	{Sine: 0},
	{Player: 0},
	{Type: 0},
	{Obstacle3: 0},
	{Collectible1: 0},
	{Obstacle2: 0},
	{Obstacle1: 0},
	{Touch: 0},
	{Text: 0},
	{Anchor: 0},
	{Sprite: 0},
	{redplaybuttonicon: 0},
	{FireworkParticles: 0},
	{Tween: 0},
	{smoke2: 0},
	{Sine2: 0},
	{Rotate: 0},
	{Obstacles: 0},
	{Collactibles: 0},
	{ObstaclesScrollingSpeed: 0},
	{canScroll: 0},
	{PlayerY: 0},
	{Score: 0},
	{type: 0},
	{x: 0},
	{y: 0},
	{count: 0},
	{combination: 0}
];

self.InstanceType = {
	Player: class extends self.ISpriteInstance {},
	Obstacle3: class extends self.ISpriteInstance {},
	Collectible1: class extends self.ISpriteInstance {},
	Obstacle2: class extends self.ISpriteInstance {},
	Obstacle1: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Text: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	redplaybuttonicon: class extends self.ISpriteInstance {},
	FireworkParticles: class extends self.IParticlesInstance {},
	smoke2: class extends self.ISpriteInstance {},
	Obstacles: class extends self.ISpriteInstance {},
	Collactibles: class extends self.ISpriteInstance {}
}